services:
  jahia:
    image: jahia/jahia-discovery:latest
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      JPDA: true
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/start" ]
      interval: 5s
      timeout: 1s
      retries: 30
